- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - static_vars.yml
    - user_defined_vars.yml
  tasks:
    - name: Create NSX Next Generation Gateway
      vmware.ansible_for_nsxt.nsxt_policy_tier1:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx.username }}"
        password: "{{ nsx.password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "NSX-NEXTGEN-GATEWAY"
        route_advertisement_types:
        - "TIER1_CONNECTED"
        tier0_display_name: NSX-GATEWAY
        locale_services:
        - edge_cluster_info:
            edge_cluster_display_name: edge-cluster-01
          state: present
          id: nsxgateway-localservices
        state: "{{ state }}"

    - name: Get Edge Cluster Id
      vmware.ansible_for_nsxt.nsxt_edge_clusters_facts:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx.username }}"
        password: "{{ nsx.password }}"
        validate_certs: "{{ validate_certs }}"
      register: edge_clusters

    - name: Print edge cluster id
      ansible.builtin.debug:
        msg: "{{edge_clusters.results[0].id}}"

    - name: Enable URL Database on the edge cluster
      uri:
        method: PATCH
        url: https://{{ nsx_node1.mgmt_ip }}/api/v1/infra/sites/default/enforcement-points/default/edge-clusters/{{edge_clusters.results[0].id}}/url-categorization-configs/default
        user: "{{ nsx.username }}"
        password: "{{ nsx.password }}"
        body:
          enabled: true
        body_format: json
        force_basic_auth: yes
        validate_certs: no

    - name: Enable FQDN analysis on the edge cluster
      uri:
        method: PATCH
        url: https://{{ nsx_node1.mgmt_ip }}/api/v1/infra/sites/default/enforcement-points/default/edge-clusters/{{edge_clusters.results[0].id}}/fqdn-analysis-config
        user: "{{ nsx.username }}"
        password: "{{ nsx.password }}"
        body:
          enabled: true
        body_format: json
        force_basic_auth: yes
        validate_certs: no
    

    - name: Create Next Generation Gateway Firewall DNS Snooping Outbound Policy
      vmware.ansible_for_nsxt.nsxt_policy_gateway_policy:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx.username }}"
        password: "{{ nsx.password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "DnsPolicy"
        id: "DnsPolicy"
        state: "present"
        sequence_number: 10
        rules:
          - action: "ALLOW"
            sequence_number: 1
            display_name: "DnsSnooping"
            id: "DnsSnooping"
            source_groups: ANY
            destination_groups: ANY
            services: ANY
            ip_protocol: IPV4_IPV6
            services: ["/infra/services/DNS" , "/infra/services/DNS-UDP"]
            profiles: ["/infra/context-profiles/DNS"]
            scope:
            - /infra/tier-1s/NSX-NEXTGEN-GATEWAY

    - name: Create URL filtering default policy
      vmware.ansible_for_nsxt.nsxt_policy_gateway_policy:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx.username }}"
        password: "{{ nsx.password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "FQDNFiltering"
        id: "FQDNFiltering"
        state: "present"
        sequence_number: 20
        rules:
          - action: "ALLOW"
            sequence_number: 1
            display_name: "DefaultCategoryBasedFiltering"
            id: "DefaultCategoryBasedFiltering"
            source_groups: ANY
            destination_groups: ANY
            services: ANY
            ip_protocol: IPV4_IPV6
            profiles: ["/infra/l7-access-profiles/default-l7-access-profile"]
            scope:
            - /infra/tier-1s/NSX-NEXTGEN-GATEWAY

